# Generated by Django 6.0.3 on 2026-03-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='mensagem_credenciamento',
            field=models.CharField(default='Esta assembleia está na fase de credenciamento e envio de documentos.', help_text='Aviso exibido no painel inicial durante a fase de inscrições.', max_length=255),
        ),
        migrations.AlterField(
            model_name='eleitor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
